### ISSUE TITLE
Refactor TeamController

### ISSUE THREAD

**Issue by JitkaCNGroup** [JitkaCNGroup/lentils#12]

**Comment by crlikcngroup** [comment]
Na tohle tam byl nějaký PR. Nebo je to tohle ještě otevřené?

**Comment by JitkaCNGroup** [comment]
tahle větev sice je merge, ale chybi chytani vyjimek pri zadavani spatných vstupnich dat ve formulari, k tomu potrebuju help a udelala jsem to nejak, neni to spatne, ale Martin navrhoval prepsat z duvodu lepsi citelnosti. Kouknu na to v souvislosti s delanim dalsiho kontroleru. Proto tady to isssue zustalo
