### ISSUE TITLE
Login form template

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#123]
Hezčí šablona pro login formulář s nějakýma barvama, případně logem CN Group.
Formulář by měl být responzivní i pro malé mobilní zařízení.

**Comment by mjanousek** [comment]
Sablona bude obsahovat:
Nadpis "Lusteniny"
Username input
Password input
Tlacitko pro prihlaseni
Logo CN Group (s odkazem na CN Jobs: https://www.cnjobs.dk/)
Obrazek na pozadi muze byt pouzity z normalniho webu: https://github.com/mjanousek/lusteniny/tree/master/web/images
Navrh:
![image](https://user-images.githubusercontent.com/12159436/55774666-6fdf2500-5a96-11e9-9ebe-37de8a156099.png)

**Comment by crlikcngroup** [comment]
Background je supr, ale šlo by to ještě nějak zkomprimovat? small-logo má pořád nějakých 750kB.
Pro použití na datech se mě to zdá pořád moc.

**Comment by mjanousek** [comment]
Jasne ze slo ;)

**Comment by mjanousek** [comment]
Btw: Prvni navrh byl s cervenym pozadim, tak kdyztak dame to, kdyz by to vypadalo blbe zkomprimovane ;)

**Comment by crlikcngroup** [comment]
@mjanousek Hodil jsem PR s prvni verzi, jestli si to jeste nezacal. Pokud uz to mas, klidne zavri.
