### ISSUE TITLE
Generovani username

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#132]
Je potreba vytvorit smysluplny username z nazvu tymu. Navrhovana strategie je:
1. mezery nahradi za podtrzitko "_"
2. nahradit ceske znaky ekvivalenty bez hacku a carek (OPTIONAL)
3. vsechny pismena mala
4. omezit pocet slov na 4

Pokud nepujde jednoduse prevest ceske znaky na mezinarodni, pak overit, ze neni problem s prihlasovanim s ceskymi znaky

Pr.:
Tym: "Veselé kočky pod střechou"
Vygenerovany username: vesele_kocky_pod_strechou

**Comment by daweedek2** [comment]
Resolved in PR #142
