### ISSUE TITLE
Client - Zobrazení final place

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#140]
Final place bude zobrazeno na konci seznamu šifer.

Zobrazí se hodinu před závěrečným vyhlášením. Nebo když tým vyluští poslední šifru.

**Comment by JurcaPavel** [comment]
Na detailu poslední šifry by neměl být odkaz na další šifru, ale na final place.

**Comment by mjanousek** [comment]
Pridavam wireframe pro zobrazeni informace o finalnim miste v listu sifer a taky detailu finalniho mista
<img width="335" alt="Screenshot 2019-04-21 at 14 20 09" src="https://user-images.githubusercontent.com/12159436/56469969-b478a200-6440-11e9-96f7-0115d3176d53.png">
<img width="336" alt="Screenshot 2019-04-21 at 14 18 56" src="https://user-images.githubusercontent.com/12159436/56469970-b478a200-6440-11e9-9073-d34c0d98693b.png">

**Comment by JurcaPavel** [comment]
detail na nové url /finalplace; zohlednit zobrazení po nějaké době - udělat zvláštní kontroler; vykuchat cypherdetail template ; vyhlášení proběhne dnes v qq -> alert dialog

**Comment by JurcaPavel** [comment]
hotovo
