### ISSUE TITLE
Admin: Pridat do formulare sifry 2 nove fieldy

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#157]
Pridat:
 - bonusContent
 - placeDescription
Fieldy jsou jiz v Cypher entite a je potreba je ukladat/editovat ve formulari sifry.

**Comment by mjanousek** [comment]
Zaroven pridat overeni:
 - nemuzou byt v poradi zadane cisla <= 0
 - musi byt zadano misto v mape

**Comment by daweedek2** [comment]
Resolved in PR #169
