### ISSUE TITLE
Google maps neumoznuje otevrit mapy s markerem na zadanem miste

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#174]
Google maps nenabizi moznost jak otevrit mapy s markerem na zadanych souradnicich. Musime najit jiny zpusob. Drive toto google podporoval, ale v aktuani verzi uz to neni podporovano. Na nejakych gps souradnicich marker zobrazi, ale na jinych ne a proto na to nemuzeme spolehat a musime najit jiny zpusob.

**Comment by mjanousek** [comment]
Odebrat tlacitko "Zobrazit na mape" a povolit mape ovladaci prvky. Tj odstranit radky:
```js
disableDefaultUI: true,
gestureHandling: 'none',
```

**Comment by JanaCNGroup** [comment]
mapa se musi otevirat v nove zalozce

**Comment by JanaCNGroup** [comment]
Pull Request #242 - jenom na otevirani v nove zalozce
