### ISSUE TITLE
BUG - Client - Zobrazuje jeden pouzity hint po zahajeni hry

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#183]
Po zahajeni hry zobrazuje senam sifer jednen pouzity hint
<img width="748" alt="Screenshot 2019-04-22 at 09 02 03" src="https://user-images.githubusercontent.com/12159436/56488053-85fcd480-64dd-11e9-8204-543e5ae6a644.png">

**Comment by daweedek2** [comment]
test steps:
vezni hint
dej solved
dej pending (organizator)
-> vidis

**Comment by crlikcngroup** [comment]
Potvrzeno.

Zobrazuje se nápověda, kterou si vzal cizí tým.

Celý postup reprodukce:

1/ Měj v systému šifry.
2/ Vytvoř tým A a tým B
3/ Přihlas se za tým A a zahaj hru
4/ Vem si nápovědu (v db je jeden záznam v hint_taken, team_id odkazuje na team A)
5/ Odhlaš se
6/ Přihlaš se jako tým B a zahaj hru
7/ Team B vidí, že si vzal nápovědu (viz Martinův screenshot) -> but, not OK

**Comment by crlikcngroup** [comment]
Tam to vypadá ještě na drobnou chybku v tom SQL dotazu pro CypherGameInfo.
Jestli se do toho nekdo pusti, napsat nejdrive test, ktery na te chybe failne a v druhem commitu opravu prosim.

**Comment by crlikcngroup** [comment]
@mjanousek Co ten dotaz v te CypherGameInfo ma presne vracet? Kazdou kombinaci pro tym a sifru?

Tzn. mam 2 tymy a 2 sifry, tak findAll by melo vracet 4 radky?

**Comment by mjanousek** [comment]
Jj. Jedine co bude zgruple bude pocet vzitych hintu.
