### ISSUE TITLE
team - spravne vyresena Zlinska sifra - zobrazit dalsi sifru - ERROR

### ISSUE THREAD

**Issue by JitkaCNGroup** [JitkaCNGroup/lentils#213]

**Comment by crlikcngroup** [comment]
@JitkaCNGroup Kdyby si náhodou měla chvilku, můžeš napsat co tady přesně bylo špatně? Tu chybu asi nemůžu reprodukovat nebo nevím o co šlo. Děkuji.

**Comment by crlikcngroup** [comment]
Již opraveno.
