### ISSUE TITLE
Back button na FinalPlace obrazovce

### ISSUE THREAD

**Issue by JurcaPavel** [JitkaCNGroup/lentils#217]

**Comment by mjanousek** [comment]
Pridat backbutton na:
- final place view
- list of hints view
- cypher detail
Nepridavat na list sifer (neni kam se vratit)
![Screenshot 2019-04-30 at 15 44 47](https://user-images.githubusercontent.com/12159436/56966277-0ca95580-6b5f-11e9-8420-b8fc26039146.png)
