### ISSUE TITLE
All cyphers in Locked status - list of cyphers is empty for user

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#221]
Pokud tym zahaji hru a organizator zmeni stav vsech sifer na locked - tym nevidi zadnou sifru ->
nemelo by se aspon neco zobrazit?

**Comment by crlikcngroup** [comment]
Tam se podle me bude muset vymyslet nejaka kontrola, aby organizator zase nemohl menit co ho napadne a aby tak nemohl dostat system do spatneho stavu.

**Comment by daweedek2** [comment]
kdyz organizator nebude mit moznost nastavit status do Locked, tim padem by se nemel dostat system do spatneho stavu (snad)

**Comment by daweedek2** [comment]
na zacatku se nastavuje prvni na pending a zbytek na locked

**Comment by daweedek2** [comment]
Related #274
