### ISSUE TITLE
Organizátor - možnost vyhledat tým 

### ISSUE THREAD

**Issue by JurcaPavel** [JitkaCNGroup/lentils#223]
Pokud bude třeba 30 týmů, bude se specifický tým organizátorům těžko hledat. Bylo by dobré kdyby jen napsali třeba pin a našlo by jim to ten tým.

**Comment by crlikcngroup** [comment]
Beru jako pokročilejší funkci, ale jako dobrý nápad :+1: 

Přidal bych nad tabulku input pro filtrování, ale místo PINu bych  hledal podle názvu týmu. Přece jen PIN slouží pro ověřování a neměl by se používat úplně všude.
