### ISSUE TITLE
Pridat logovani

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#224]
Poud se neco pokazi, bylo by dobre mit logovani a z logovani vycist, kdo vyhral
 - vymyslet format logovani
 - identifikovat vsechny mista, ktere by bylo dobre logovat
 - pridat logovani
 - najit zpusob, jak vyfiltrovat z logu logy pro urcity team pop.r neco dalsiho.

Co chceme logovat:
Client
- u kazde z akci nize vypisovat i celkovy pocet
- uspesne/neuspesne zaslani formulare na overeni hesla (team, sifru, vysledek (i body))
- ziskani hintu (team, hint, pocet bodu, sifra)
- preskoceni sifry (team, sifra)
Organizator
- zmena stavu sifry (team, sifra, body)
- ziskani hintu (team, sifra)

**Comment by crlikcngroup** [comment]
Co se formatu tyce, co treba tohle:

[<TIME>] '<action>' by (organizer|team) #<id> <name> (for team #<id> teamName), <action-data>, body: <celkovy-pocet-bodu-tymu>

Priklad:
[2050-01-02 08:00] 'solve-cypher' by team \#12 testTeam, value 'kakao', 

[2050-01-02 08:00] 'skip-cypher' by team \#12 testTeam, cypher \#43 Zlinska sifra, body: 25
[2050-01-02 08:00] 'skip-cypher' by organizer \#31 Emil for team \#12 testTeam, cypher \#43 Zlinska sifra, body: 25
