### ISSUE TITLE
Game - aktualni skore chybi v menu pro cypher detail a hint page

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#267]
Header zobrazuje aktualni skore jen na listu sifer.

![image](https://user-images.githubusercontent.com/47707682/57196950-e5d58f80-6f61-11e9-8f84-1cd4cc5c63f4.png)

Ostatni view (cypher detail a hint detail) aktualni skore zobrazeno nemaji.

![image](https://user-images.githubusercontent.com/47707682/57196940-d9513700-6f61-11e9-959a-ed2048e74f72.png)

**Comment by JurcaPavel** [comment]
mám pocit že tohle mám už rozdělané na lokálu

**Comment by JanaCNGroup** [comment]
Zrovna jsem se na to zacala divat, tak ti to mam nechat a ulovit si neco jineho?

**Comment by JurcaPavel** [comment]
ok :)
