### ISSUE TITLE
Make map link of the cypher required

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#279]
Pokud neni vytvorena sifra ktera obsahuje odkaz na mapu, tak se po kliknuti Zobrazit na mape nic nestane -> takze bych udelal policko MapAddress jako required :)

**Comment by daweedek2** [comment]
to je otazka ;)

**Comment by mjanousek** [comment]
@David no to teda neni! :D

**Comment by mjanousek** [comment]
Tak jo, je :D
