### ISSUE TITLE
Hledani pomoci GET requestu

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#302]
vyhledavani je ted udelane v samostatnem POST requestu.

je potreba to zmenit na GET request a nejlip nevytvaret nove url, ale pouzit jiz existujici (../stage, ../teamList)

**Comment by mjanousek** [comment]
Teto issue moc nerozumim. Muzes to prosimte vic rozvest?

**Comment by crlikcngroup** [comment]
@mjanousek Má to teď udělaný formulár pro vyhledávání, který ale posílá POST, který dokonce nedělá redirect, ale renderuje šablonu.

Přišlo by mě šťastnější mít ten formulář, který posílá GET a řetězec pro hledání je tak i standardně součástí url. Např. /teams?search=foobar.

Odpadají problémy s tlačítkem zpět, vyhledávání jde ukládat atd...

Původní PR je tady: https://github.com/JitkaCNGroup/lentils/pull/299, David si na tuhle změnu vytvořil zvlášť issue.
