### ISSUE TITLE
Admin - "Akce" dropdown nefunguje

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#307]
![image](https://user-images.githubusercontent.com/47707682/57646377-b6a5ca80-75c0-11e9-8312-c473c72406c3.png)

v listu sifer nebo listu tymu, tlacitko dropdown nefunguje - po kliknuti je error v konzoli:

![image](https://user-images.githubusercontent.com/47707682/57646292-8827ef80-75c0-11e9-89c8-b8ddbc8347ba.png)

**Comment by JurcaPavel** [comment]
tak aspoň už víme proč byla potřebná ta knihovna Popper.js :D
