### ISSUE TITLE
Pridat codeword do detailu sifry pod nadpis

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#311]
Pridat codeword do organizacni casti pod nazev sifry tak, aby si ho mohl Organizator zkontrolovat. Idealni by bylo, kdyby nebylo zobrazene porad, ale jen kdyz na nej organizator klikne a nebo na nejake tlacitko vedle nej. Prvni navrhnete a diskutujte reseni a az pak se pustte do implementace ;)

**Comment by JurcaPavel** [comment]
Navrhuji, aby tam prostě bylo tlačítko zobrazit řešení a to by měnilo textu s řešením pod tím visibility.
