### ISSUE TITLE
Zmenit hesla pro admina a organizatora na serveru

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#339]

**Comment by crlikcngroup** [comment]
Mám to nastavit náhodně a pak vám to poslat? Nebo jak to udělat?

**Comment by mjanousek** [comment]
Mozna bych udelal jeste jeden sql, ktery bude obsahovat jen prenastaveni hesel pro admina a organizatora. Kdyz dumpnem databazi, tak uz potrebovat nebude, ale zatim kdyz ji smazem, se to pak muze jen pustit. Klidne muzu ty dva updaty nachystat. Co myslis ty @CrNix ?
