### ISSUE TITLE
User - Obrazek napovedy se zobrazuje i kdyz neni vlozeny

### ISSUE THREAD

**Issue by KarolinaNesrstova** [JitkaCNGroup/lentils#343]
![image](https://user-images.githubusercontent.com/49400971/58104677-73adad80-7be5-11e9-9044-24a0b58d3412.png)

Pokud v napovede neni pouzity obrazek, nemel by se zobrazovat text "Obrazek napovedy".
(Stejne se zobrazuje i z pohledu organizatora.)

**Comment by crlikcngroup** [comment]
Snažil jsem se to opravit. PR #346.
Jak to bude na serveru, dám vědět.

**Comment by KarolinaNesrstova** [comment]
Verified in v1.0.1
