### ISSUE TITLE
Client - back button background color

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#348]
![image](https://user-images.githubusercontent.com/47707682/58149020-74842500-7c61-11e9-814e-587ffd87d597.png)

**Comment by crlikcngroup** [comment]
To je u klienta? Hmmm, lokálně nebo na serveru?

**Comment by daweedek2** [comment]
lokalne

**Comment by daweedek2** [comment]
pull masteru a spusteni aktualni verze -> vypada to ze se to zobrazuje spravne

**Comment by crlikcngroup** [comment]
Měl si to v Chromu? Já na to ve Firefoxu nenarazil, možná nějaká chybka s tím HTML.

**Comment by daweedek2** [comment]
chrome, presne tak

**Comment by crlikcngroup** [comment]
Zatím se mě nedaří reprodukovat.
(Firefox, Brave, Chrome, mobilní Chrome)

**Comment by daweedek2** [comment]
taky se mi to nepodarilo reprodukovat..
