### ISSUE TITLE
ADMIN - místo vyhlášení - validace času neukáže error při zadání špatného inputu

### ISSUE THREAD

**Issue by JurcaPavel** [JitkaCNGroup/lentils#351]

**Comment by JanaCNGroup** [comment]
Pavle mohl bys upresnit, co jsi tim myslel? Cas ani datum se nedaji zadat mimo svuj rozsah (ale je fakt, ze kdyz to zadas mimo rozsah, tak to automaticky opravi a nenahlasi chybu). Da se tam teda nastavit uz probehle datum a cas, ale to asi neni chyba, nebo je?

**Comment by JurcaPavel** [comment]
Zapomněl jsem dodat - testováno na FIREFOXu. Možná to u ostatních prohlížečů funguje dobře :)

**Comment by JurcaPavel** [comment]
Přikládám obrázek a jdu se opět učit! 🤙 🤙 
![image](https://user-images.githubusercontent.com/43091754/58337543-4c095000-7e46-11e9-8f30-ac31dc5e7379.png)

**Comment by daweedek2** [comment]
vytvorim validaci na cas v minulosti + format casu

**Comment by daweedek2** [comment]
![image](https://user-images.githubusercontent.com/47707682/58398862-a5e06480-8056-11e9-80e7-d949507de105.png)

![image](https://user-images.githubusercontent.com/47707682/58398880-b0026300-8056-11e9-86b6-a5b5c2e8fabe.png)

**Comment by crlikcngroup** [comment]
*Firefox nepodporuje type="localDateTime" pro input prvek.
Chrome a Safari zobrazi picker.

Jeste bych pridal placeholder s tim formatem, co je potreba zadat, pokud ho input nema.

**Comment by crlikcngroup** [comment]
@mjanousek @daweedek2 @KarolinaNesrstova @JanaCNGroup @JitkaCNGroup Ještě dotaz. Chceme tu kontrolu na čas v minulosti? Co testy? Není to tam někdy potřeba nastavit na takový čas?
Narazil jsem na to a párkrát jsem to potřeboval nastavit, ale UI mě to takhle nenechá.

**Comment by daweedek2** [comment]
Validaci na čas v minulosti odstraníme

**Comment by daweedek2** [comment]
verified on firefox, chrome, edge
29.5.2019 15.18

**Comment by mjanousek** [comment]
Tohle uz muzeme teda zavrit?

**Comment by daweedek2** [comment]
za mě je to OK

**Comment by crlikcngroup** [comment]
Opraveno.
