### ISSUE TITLE
Admin - Cypher form - move Adresa mapy field

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#359]
bylo by fajn, kdyby vsechny required fieldy byly pohromade (posunout Adresa mapy pod Souradnice

**Comment by crlikcngroup** [comment]
Admin a Organizátor?
Jo, přeházet se to asi postupně může. První povinné položky a pak ty ostatní?

**Comment by daweedek2** [comment]
hlavne Admin :)
