### ISSUE TITLE
V admin nejde zjistit / nastavit hodnotu šifry

### ISSUE THREAD

**Issue by JitkaCNGroup** [JitkaCNGroup/lentils#361]
**TC Organizer009 - score calculation**, 2.precondition, "cypher1 with value 10, cypher2 with value 20, cypher3 with value 30"

Tri cesty k reseni : 1/ upravit TC a predpokladet, ze kazda sifra ma konstantni hodnotu
2/ nastavit sifram ruznou hodnotu, ale mit moznost ji zobrazit v adminovi a s touto hodnotou pracovat v TC
3/ v admin nastavit a cist hodnotu sifry

**Comment by JitkaCNGroup** [comment]
Spolecne s Davidem zjisteno, ze hodnota šifry je v kodu natvrdo. Společně s Davidem hm, hm.

**Comment by crlikcngroup** [comment]
Myslíte počet bodů, které tým dostane, když šifru vyluští?

Jo, to je natvrdo. Počítá se stejným počtem bodů za každou šifru. Momentálně je to jako loni 10 bodů.

**Comment by mjanousek** [comment]
Presne tak, za kazdou sifru je 10 bodu - toto zatim menit urcite nebudeme.
