### ISSUE TITLE
Game008 - view finalplace - cyphers skipped

### ISSUE THREAD

**Issue by JitkaCNGroup** [JitkaCNGroup/lentils#362]
There is an information that team skipped the cypher2. In fact there were 4 cyphers and all were skipped. 
There is a button Zobrazit misto vyhlaseni present.
ok
Step Verify that the footer with finalplace button and time is displayed.
fail - there is no footer with informations
![bug](https://user-images.githubusercontent.com/42601181/58261292-4d6c4700-7d78-11e9-935d-6b850ea0f571.JPG)

**Comment by JanaCNGroup** [comment]
Podle mě se nejedná o bug, jenom o trochu jinak napsaný testCase - porovnala jsem s Game007 cyphers solved, výsledek je úplně stejný v obou případech:

![image](https://user-images.githubusercontent.com/49236926/58326609-9d591580-7e2d-11e9-8473-16b39f5c26f2.png)

V Game007 je navíc krok Go back to the cypher list, kde se ten footer opravdu zobrazuje, kdežto v Game008 tento krok chybí a ověřuje se, zda se footer zobrazuje přímo na poslední šifře - což se nezobrazuje.

Asi by tedy na vyřešení bugu stačilo mírně upravit testCase Game008
