### ISSUE TITLE
Dalsi sifra se hleda podle ID

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#384]
je tam funkce, tera hleda dalsi sifru.
Melo by to by podle poradi. Momentalne se to bere podle ID. To je chyba.

Vypada to, ze po vyreseni sifry klientem se spatne nastavi nasledujici sifra.

**Comment by crlikcngroup** [comment]
Vytvořil jsem nový tým a prošel všema šiframa z mobilu. Šli  přesně v tom pořadí jako jsou zobrazeny v Admin sekci.

To je to co nefungovalo a mělo by takto jít? Jestli ano, tím pádem bych to bral jako úspěšný test :)

**Comment by mjanousek** [comment]
Ano, presne to nesloa melo by jit ;)
