### ISSUE TITLE
[Client] Vyhlášení výsledků vyhodí HTTP 500

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#386]
Potřeba reprodukovat.

Po stisku tlačítka Vyhlášení výsledků na poslední šifře.

**Comment by mjanousek** [comment]
1. Problem: Nekonzistence:
 - tacitko "Zobrazit vyhlaseni vysledku" se zobrazi na detailu v pripade, ze uz neni zadna dalsi sifra
 - tacitko "Zobrazit vyhlaseni vysledku" se zobrazi na listu v pripade, ze nadesel spravny cas a vse je vylusteno
2. FinalPlaceController vyhodi vyjimku, pokud nejsou vsechny sifry dolusteny a zaroven pokud nadesel spravny cas.
Navrhovane reseni:
1. FinalPlaceController bude vyhazovat vyjimku pouze, pokud nejsou dolusteny vsechny sifry
2. Na seznamu sifer se tlacitko zobrazi bud v pripade, ze vyhlaseni probehne za min nez hodinu a nebo v pripade, ze vsechny sifry jsou dolusteny.
