### ISSUE TITLE
[Organizer] nemenit stav nasledujici sifry po restartu

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#397]
Pokud organizer restartuje napriklad 2. sifru tymu, ktery uz ma vylustenych 8 sifer, pak se 3. sifra dostane do stavu locked. To same plati, pokdu ji pak vrati do puvodniho stavu (solved, skipped), pak ta 3. sifra se zmeni do stavu pending. Tj chce to menit stav nasleduici sifry pouzi v pripade, ze vsechny nasledujici sifry jsou ve stavu locked. Pro jistotu nad tim jeste vic popremyslejte.

**Comment by JanaCNGroup** [comment]
pridala jsem k tomu problem, kdy pokud organizator zmeni  uz vylustenou sifru do stavu pending a tim padem je tam vic pending sifer pro jeden tym, zobrazuje se v aktualnim stage tymu porad ta posledni pending sifra - mela by tam byt naopak prvni pending sifra.
