### ISSUE TITLE
[Client] Wrong order of cyphers

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#398]
Spatne poradi sifer u klienta. Je to zpusobene metodou `CypherGameInfoService.getAllByTeamIdAndStatusIsNotLocked`, ktera obsahuje volani metody `cypherGameInfoRepository.findAllByTeamId`, ktera vraci sifry serazene podle ID a nahradit ji za metodu `cypherGameInfoRepository.findAllByTeamIdOrderByStageAsc`

**Comment by mjanousek** [comment]
![Screenshot 2019-06-04 at 18 49 55](https://user-images.githubusercontent.com/12159436/58898462-ed23c080-86fa-11e9-90d2-b9a9bfe43702.png)

**Comment by crlikcngroup** [comment]
Otestováno.

Šifry se teď vždy v seznamu řadí podle stage number.
