### ISSUE TITLE
[Admin] Pridat indikaci do tabulky napoved, ze obsahuje obrazek

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#440]
Pridat nejaky sloupec treba s checkboxem, ze napoveda obsahuje obrazek.

**Comment by daweedek2** [comment]
![image](https://user-images.githubusercontent.com/47707682/60164719-5ed4c300-97fe-11e9-9d93-e22ee24411d0.png)

muze byt?

**Comment by mjanousek** [comment]
Supr ;)
