### ISSUE TITLE
[Admin|Client|Organizer] Final place upgrade

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#444]
Chceme rozlisit cas konce sifrovacky a zacatek vyhlaseni vitezu.
- Rozsirit final place (entity, DB) "finish time" atributem.
- Prejmenovat openingTime na neco vhodnejsiho specifikujci, ze je to cas zahajeni toho vyhlaseni vitezu.
- Upravit logiku, kde se kontroluje, zda hra jeste nezkoncila
- zobrazovat spravny cas vyhlaseni vitezu

**Comment by daweedek2** [comment]
openingTime -> finishTime
cas vyhlaseni -> resultsTime

assertion: finishTime < resultsTime
