### ISSUE TITLE
Potencialni NPE v ProgressService::getStageOfPendingCypherForTeam

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#486]
Volá se get bez toho, abz se kontrolovalo jestli findFirst vůbec něco vrátí a dál se s výsledkem pracuje.

Může se stát, že se někdy vrátí prázdný výsledek?

**Comment by daweedek2** [comment]
ja si myslim ze nemuze, protoze kazda sifra musi mit ulozenou stage:
`    @Column(name = "stage")
    @NotNull(message = "Pořadí nesmí být prázdné.")
    @Min(value = 1, message = "Pořadí musí být větší než 0.")
    private int stage;`
