### ISSUE TITLE
Přejmenovat balíček dk.cngroup.lentils.entity.form

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#488]
camelCase není v konvencích pro název balíčku. Jsou povolené jen malé písmena.

Přesněji: ^[a-z_]+(\.[a-z_][a-z0-9_]*)*$

**Comment by mjanousek** [comment]
Videl bych to na: 
`dk.cngroup.lentils.entity.form`
a nebo
`dk.cngroup.lentils.dto` (pokud jsou v tom dto, tak toto by byla lepsi varianta)

**Comment by crlikcngroup** [comment]
Tak objekty dát do ```dk.cngroup.lentils.dto``` a konvertory nechat kde jsou, v ```dk.cngroup.lentils.service.converters``` ?

A ty objekty pak pojmenovávat třeba ContactFormDTO, ContactApiDTO, UserSecurityDTO atd?

**Comment by mjanousek** [comment]
Jop, to za me klidne muze byt.
