### ISSUE TITLE
Optimaliazce: Pouzit StringBuilder v TeamScoreDetail::toString

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#490]
V cyklu se znovu vytvari String. Lepsi je pouzit StringBuilder a sestavit retezec takhle.

**Comment by crlikcngroup** [comment]
Jen pro zajímavost: ještě existuje třída StringBuffer, která je navíc thread-safe (ale tady to není potřeba) 👍

**Comment by JurcaPavel** [comment]
Mohu to vyřešit i takto? `public String toString() {
        return hintsTaken.stream()
                .map(hintTaken -> hintTaken.getHint().getHintId().toString())
                .collect(Collectors.joining(", "));
    }`
