### ISSUE TITLE
Start game and initialization solving

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#50]
Initialization should be done at the Start of the game.

**Comment by mjanousek** [comment]
- zobrazit tlacitko pro zahajeni hry na endpointu /cypher (aktualne je tam list sifer)
- po kliknuti se inicializuje DB: 
    - pro dany team se prvni sifra nastavina PENDING
    - pro dany team se vsechny ostatni sifry nastavi na LOCKED
- po kliknuti na tlacitko by mela byt v seznamu prvni sifra

**Comment by daweedek2** [comment]
po kliknuti na tlacitko by mela byt v seznamu prvni sifra
-> nově: po kliknuti na tlacitko je zobrazen seznam vsech sifer

Resolved in the PR #154
