### ISSUE TITLE
Map is not loaded - cannot create cypher!

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#566]
když se vytváří šifra, mapa nejde načíst 
![image](https://user-images.githubusercontent.com/47707682/66023005-02b1c700-e4f0-11e9-8967-6a7e3d0e606f.png)

error v konzoli:
![image](https://user-images.githubusercontent.com/47707682/66023113-77850100-e4f0-11e9-9c86-52daf66a26fe.png)

**Comment by mjanousek** [comment]
We probably must change google maps with a different library.

**Comment by CrNix** [comment]
Martin se stal sponzorem a zapnul platby. Prej uz to jede.
