### ISSUE TITLE
Refactoring of URL for the main part of the system

### ISSUE THREAD

**Issue by mjanousek** [JitkaCNGroup/lentils#58]
We have 3 main parts of the system:
- data definition (create cyphers, hints, etc) (admin)
- competitors part (this part will be used by competitors during the game)
- organizators part (this part will be used by organizators during the game)
The structure of packages and url paths should reflect this division. It means that we have to refactor structure of controllers, their urls etc. I suggest these urls:

- .../admin/... for admin part
- .../... for users
- .../game/... for organizators part

**Comment by daweedek2** [comment]
https://github.com/JitkaCNGroup/lentils/pull/94
