### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by crlikcngroup** [JitkaCNGroup/lentils#77]
Mohli by jsme nahodit nejakou jednoduchou favicon ikonku misto te originalni pro Tomcat.

**Comment by crlikcngroup** [comment]
Generate favicon by favicon.io

**Comment by mjanousek** [comment]
[favicon_io.zip](https://github.com/JitkaCNGroup/lentils/files/3067104/favicon_io.zip)
Favicon obrazky
