### ISSUE TITLE
wrong PIN alert is displayed multiple times 

### ISSUE THREAD

**Issue by daweedek2** [JitkaCNGroup/lentils#87]
kdyz se zada spatny pin pri brani hintu v admin casti, vyskoci 1 alert - OK,
pokud zada spatny pin podruhe, vyskoci 2 alerty, atd atd atd

**Comment by crlikcngroup** [comment]
Ty jo, to uniklo review :) Tam se navazuje handler pri kazdem otevreni dialogu. Element jich muze obsahovat vic. Staci vyhodit nasledujici kod z funkce openDialog ven:
```
$("#verifyBtn").click(function () {
        verifyPinPost(hintId);
        $('#takeHintModal').modal('hide');
        $(".modal-body input").val("");
});
```

**Comment by daweedek2** [comment]
A bude v te funkci verifyPinPost zadaný správný parametr hintId?

**Comment by crlikcngroup** [comment]
Právě to chce předat trochu jinak. Máš pravdu. Bez dalších opiček co mají některé JavaScript frameworky, jsem to přepsat trochu old-schoolově.
Ještě s pár věcma, jsem to zkusil opravit v PR #97.
